 ```yml
   theme: minima
   title: Statistics, Probability and Econometrics for Finance and Accounting Students
   author: Matthew L. Kelly
   description: A course in data analysis using Python
   
   ```
